In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.2.3'

In [3]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [4]:
df.head(10)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   
5                  190            3.0         NaN     2484.883986   
6                  240            7.0       127.0     3006.542287   
7                  150            4.0       239.0     3638.657780   
8                  250            1.0       174.0     2714.219310   
9                  150            4.0       123.0     3509.036569   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   
5          14.7        2008  Europe  Gasoline    All-wheel drive       -1.0   
6          22.2        2012     USA  Gasoline  Front-wheel drive        1.0   
7          17.3        2020     USA    Diesel    All-wheel drive        1.0   
8          10.3        2016    Asia    Diesel  Front-wheel drive       -1.0   
9          10.2        2005     USA  Gasoline  Front-wheel drive       -1.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369  
5            17.271818  
6            13.210412  
7            12.848884  
8            16.823554  
9            12.298355

In [5]:
number_of_rows = df.shape[0]
number_of_rows

9704

In [8]:
brands = df['fuel_type']
brands.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [9]:
brands.nunique()

2

In [10]:
count = 0
for column in df.columns:
    if df[column].isnull().any():
        count += 1
count

4

In [13]:
dell_df = df[df['origin'] == 'Asia']
dell_df_sorted = dell_df.sort_values(by='fuel_efficiency_mpg', ascending=False)
dell_df_sorted.head(1)["fuel_efficiency_mpg"]

9387    23.759123
Name: fuel_efficiency_mpg, dtype: float64

In [14]:
df['horsepower'].median()

149.0

In [15]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [16]:
new_df = df['horsepower'].fillna(152.0)
new_df.median()

152.0

In [17]:
df.head(10)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   
5                  190            3.0         NaN     2484.883986   
6                  240            7.0       127.0     3006.542287   
7                  150            4.0       239.0     3638.657780   
8                  250            1.0       174.0     2714.219310   
9                  150            4.0       123.0     3509.036569   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   
5          14.7        2008  Europe  Gasoline    All-wheel drive       -1.0   
6          22.2        2012     USA  Gasoline  Front-wheel drive        1.0   
7          17.3        2020     USA    Diesel    All-wheel drive        1.0   
8          10.3        2016    Asia    Diesel  Front-wheel drive       -1.0   
9          10.2        2005     USA  Gasoline  Front-wheel drive       -1.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369  
5            17.271818  
6            13.210412  
7            12.848884  
8            16.823554  
9            12.298355

In [18]:
asia_cars = df[df['origin'] == "Asia"]
asia_cars

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [21]:
asia_cars[['vehicle_weight', 'model_year']][:7]

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [22]:
X = asia_cars[['vehicle_weight', 'model_year']][:7].to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [23]:
XT = X.transpose()
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [24]:
XTX = XT @ X
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [25]:
inverse_XTX = np.linalg.inv(XTX)
inverse_XTX

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [27]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [28]:
z = inverse_XTX @ XT
z

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [29]:
w = z @ y
w

array([0.01386421, 0.5049067 ])

In [30]:
np.sum(w)

np.float64(0.5187709081074026)